### ISSUE TITLE
only last job scheduled runs

### ISSUE THREAD

**Issue by giulianoz** [tejasmanohar/node-schedule#168]
Hi,
it seems that only the last job I put on the stack is run. I'm on node 0.12.7 + node-scheduler (latest)

example code:

var schedulerConfig={
	"jobs": {
		"job1" : "* * * * *",
		"job2" : "* * * * *"
	}
};
var fn={};
var jobs=[];
for (var i in schedulerConfig.jobs) {
	jobs[i] = schedule.scheduleJob(i,schedulerConfig.jobs[i],function(){fn[i]()});
}
fn.job1=function() { console.log('job1'); }
fn.job2=function() { console.log('job2'); }

the jobs[] contains both jobs.
Am I missing something obvious ?

thanks

g

**Comment by santigimeno** [comment]
@giulianoz What are you trying to accomplish? The code you posted is not valid: fni is not defined anywhere and "* * * * " is not a valid cron expression. See: https://github.com/tejasmanohar/node-schedule/wiki/Cron-style-Scheduling.
Rewriting your example so job1 and job2 execute both every second, I can reproduce your issue: the problem is how you define the job function: `function() {fn[i]();}`: when job1 or job2 are triggered, `i` is always `2` (after the for loop), so only `fn.job2` is executed. Rewrite it like this and it works:
```
var schedule = require('node-schedule');

var schedulerConfig={
	"jobs": {
		"job1" : "* * * * * *",
		"job2" : "* * * * * *"
	}
};
var fn={};
var jobs=[];

fn.job1=function() { console.log('job1'); }
fn.job2=function() { console.log('job2'); }

for (var i in schedulerConfig.jobs) {
	jobs[i] = schedule.scheduleJob(i,schedulerConfig.jobs[i],fn[i]);
}
```
