### ISSUE TITLE
Cancel node-schedule event after it has been set

### ISSUE THREAD

**Issue by ShahNewazKhan** [tejasmanohar/node-schedule#192]
I am planning on using node-schedule to set up push notifications for appointment reminders as follows:

    var schedule = require('node-schedule');
    var date = req.body.date;   // Date for reminder from client request 
    var j = schedule.scheduleJob(date, function(){
        // Send push notification
    });
Now I know you can cancel the event by calling cancel():

    j.cancel()

However, how can I refer to that specific job to cancel if the user from the client side decides to change the appointment to a different date later on?

For example user wants to set a reminder for December 25th 2015, then a few days later they decide to change the reminder to December 24th, 2015. 

How can I reference the event that was scheduled for December 25th, 2015 and cancel it and create a new one for December 24th, 2015. 

Thanks in advance for your help!

**Comment by santigimeno** [comment]
@ShahNewazKhan I'm not sure I understand correctly what the problem is: 
- You have problems getting a reference to a job by the scheduled date, or
- You need to be able to re-schedule a specific job.

In case your problem is the first one, I don't think there's a way to do that: you could have multiple job scheduled for the same time. In order to retrieve a specific job, you could always create it with a unique name and you could always retrieve it later via that unique name:
```
var j = schedule.scheduleJob(unique_name, date, function() {
});
 // later on
var my_job = schedule.scheduledJobs[unique_name];
```

In case you want to be able to reschedule the job, there's no specific method, but you can do:
```
var j = schedule.scheduleJob(date, function(){
    // Send push notification
});

// later on
var job_method = j.job;
j.cancel();
var new_job = var j = schedule.scheduleJob(date, job_method);
```

**Comment by tejasmanohar** [comment]
Was about to say pretty much the same thing as @santigimeno, but I'd like to mention that this really sounds like an implementation detail for your system rather than a question about node-schedule... If you could abstract all your functionality and just talk about what you need the library to do, that'd be best :)

**Comment by ShahNewazKhan** [comment]
Thanks @santigimeno, the first solution is exactly what I needed! 

@tejasmanohar You are correct, as per @santigimeno  the abstract functionality I was seeking is:

Being able to reschedule or cancel a specific job.

**Comment by tejasmanohar** [comment]
Thanks.

**Comment by santigimeno** [comment]
BTW a `reschedule` method *could* be a nice addition

**Comment by tejasmanohar** [comment]
I think so too, that would be a nice convenience method, I'll assign that to myself and knock it out early next week

**Comment by ShahNewazKhan** [comment]
@tejasmanohar if possible, could you please update this thread once the reschedule method is implemented?

Thanks in advance!

**Comment by tejasmanohar** [comment]
subscribe to #193 :)

**Comment by ShahNewazKhan** [comment]
thanks!

**Comment by esatterwhite** [comment]
what is it a convenience for? is it possible to do this in a long hand currently? what is it?

**Comment by tejasmanohar** [comment]
long-hand is here https://github.com/node-schedule/node-schedule/issues/192#issuecomment-150762650 @esatterwhite
